spring:
  application:
    name: timesheet
  datasource:
    # url: jdbc:postgresql://localhost:5432/timesheets_db
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
